In [3]:
import numpy as np

In [6]:
np.array([2,3,1])

array([2, 3, 1])

In [9]:
np.empty(5)

array([0.00e+000, 0.00e+000, 0.00e+000, 7.31e-321, 0.00e+000])

In [8]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [11]:
np.arange(6,23)

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [15]:
# Heading

In [43]:
ar = np.array([[1,2,3,4]])

In [36]:
ar2 = np.array([55,44,66])

In [20]:
array_append=np.append(ar2,ar)

In [21]:
np.sort(array_append)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 44, 55, 66])

In [23]:
bgar = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

In [27]:
bgar.shape

(3, 2, 4)

In [32]:
ar.shape

(8,)

In [30]:
medar = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

In [31]:
medar.shape

(2, 4)

In [35]:
ar3 = np.array([[1],[2],[3],[4]])

In [37]:
ar3

array([[1],
       [2],
       [3],
       [4]])

In [42]:
ar3.shape

(4, 1)

In [44]:
ar.shape

(1, 4)

In [46]:
medar = np.array ([[[0,1],[2,3],[4,5]]])

In [47]:
medar

array([[[0, 1],
        [2, 3],
        [4, 5]]])

In [48]:
medar.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [68]:
medar = medar.reshape(3,2)

In [107]:
medar4 = medar3[:, np.newaxis]

In [104]:
medar3 = medar.reshape(6,1)

medar3

In [109]:
medar4.shape

(6, 1, 1)

In [103]:
medar3.shape

(6, 1)

In [108]:
medar4

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]]])

In [111]:
bgar[bgar>5]

array([6, 7, 6, 7, 6, 7])

In [112]:
bgar

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [113]:
arstack1= np.array([[1,2],[3,4]])

In [115]:
arstack2= np.array([[5,6],[7,8]])

In [119]:
arraystack = np.vstack((arstack1, arstack2))

In [123]:
medar

array([[0, 1],
       [2, 3],
       [4, 5]])

In [125]:
medar.sum(axis=1)

array([1, 5, 9])

In [126]:
medar

array([[0, 1],
       [2, 3],
       [4, 5]])

In [128]:
print(medar[0:2,1])

[1 3]
